export const FETCH_PERSONAL_DETAILS = "Person/FETCH_PERSONAL_DETAILS";
export const FETCH_PERSONAL_DETAILS_LOADING =
  "Promotion/FETCH_PERSONAL_DETAILS_LOADING";
export const FETCH_PERSONAL_DETAILS_LOADED =
  "Person/FETCH_PERSONAL_DETAILS_LOADED";
export const FETCH_PERSONAL_DETAILS_FAILED =
  "Person/FETCH_PERSONAL_DETAILS_FAILED";
